Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(12,6))
plt.subplot(121)
kmeans1 = KMeans(n_clusters=nb_cl, init="random", n_init=1, random_state=41)
kmeans1.fit(X)
plot_decision_boundaries(kmeans1, X)
plt.title("Init1")

plt.subplot(122)
kmeans2 = KMeans(n_clusters=nb_cl, init="random", n_init=1, random_state=43)
kmeans2.fit(X)
plot_decision_boundaries(kmeans2, X)
plt.title("Init2")

plt.tight_layout()
plt.savefig("images/init.png",dpi=100)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m12[39m,[38;5;241m6[39m))
[1;32m      2[0m plt[38;5;241m.[39msubplot([38;5;241m121[39m)
[0;32m----> 3[0m kmeans1 [38;5;241m=[39m KMeans(n_clusters[38;5;241m=[39m[43mnb_cl[49m, init[38;5;241m=[39m[38;5;124m"[39m[38;5;124mrandom[39m[38;5;124m"[39m, n_init[38;5;241m=[39m[38;5;241m1[39m, random_state[38;5;241m=[39m[38;5;241m41[39m)
[1;32m      4[0m kmeans1[38;5;241m.[39mfit(X)
[1;32m      5[0m plot_decision_boundaries(kmeans1, X)

[0;31mNameError[0m: name 'nb_cl' is not defined
NameError: name 'nb_cl' is not defined

